### ISSUE TITLE
Create a todo list component

### ISSUE THREAD

**Issue by t-bowersox** [t-bowersox/vanilla-todo.bytim.dev#5]
The todo list component should allow a user to:

- Create a new todo
- View all incomplete todos

The todos will themselves be components. These will fire events to the list, which will "complete" them (i.e. remove them from the list).

---

#### Tasks

- [x] The todo data should be stored using IndexedDB.
- [x] I'd like the todo list to display a text input with a submit button for creating a new todo.
- [x] Below that should be the list of incomplete todos.
- [x] Each task should display a name and a "Complete" button.
- [x] If there are no todos, there should be default message like "You have no todos!"
